kind: Service
apiVersion: v1
metadata:
  name: java-elastic-integration
  labels:
    app: java-elastic-integration
spec:
  type: NodePort
  selector:
    app: java-elastic-integration
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-elastic-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-elastic-integration
  template:
    metadata:
      labels:
        app: java-elastic-integration
        version: v1
    spec:
      containers:
      - name: java-elastic-integration
        image: java-elastic-integration
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
